export const SET_FETCHING = "SET_FETCHING";
export const SET_FOUNDED = "SET_FOUNDED";
export const INC_TICKETS_AMOUNT = "INC_TICKETS_AMOUNT";
export const TOGGLE_FILTER = "TOGGLE_FILTER";
export const CAST_FILTERS = "CAST_FILTERS";
export const CHANGE_SORT = "CHANGE_SORT";
export const SET_SKIP_ERROR = "SET_SKIP_ERROR";
export const APPEND_TICKETS = "APPEND_TICKETS";
